### ISSUE TITLE
Support `OrElse`

### ISSUE THREAD

**Issue by isac322** [moznion/go-optional#20]
Simple usecase:

```golang
optionalResult := db.call()


# as-is
optionalResult.IfNone(func() {
  optionalResult = db.someOtherCall()
}
return optionalResult


# to-be
return optionalResult.OrElse(db.someOtherCall)
```

rust's `Option` supports this: https://doc.rust-lang.org/std/option/enum.Option.html#method.or_else

Thanks for your work!

**Comment by moznion** [comment]
Hello @isac322,
Thank you for your feature request. I implemented that at #21 and published [v0.9.0](https://github.com/moznion/go-optional/releases/tag/v0.9.0) version that provides that new `#OrElse()` method. Could you please try it?

**Comment by isac322** [comment]
@moznion I think what you added was `Or()`. `OrElse()` should accept function as parameter.

**Comment by moznion** [comment]
@isac322 Thank you for your correcting. I bumped [v0.10.0](https://github.com/moznion/go-optional/releases/tag/v0.10.0) up.
