### ISSUE TITLE
Fulfil the `sql/database/driver.Valuer` and `driver.Scan` interfaces

### ISSUE THREAD

**Issue by tonyhb** [moznion/go-optional#27]
This would allow `go-optional` to be used as nullable DB types for any backing type, deferring to the underlying type T for values.

**Comment by moznion** [comment]
Hi @tonyhb, I appreciate your suggestion.
Yeah, that sounds made sense to implement the [driver.Valuer](https://pkg.go.dev/database/sql/driver#Value) interface. But on the other hand, I'm not sure and I couldn't find the `driver.Scan` interface. Could you please give me the reference for that interface?

**Comment by moznion** [comment]
@tonyhb I implemented the `sql.Scanner` and `sql/driver.Valuer` interfaces and published that as [v0.11.0](https://github.com/moznion/go-optional/releases/tag/v0.11.0).
